// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInQWxlKfftNsEyo29U91VQqygWgr_uG0',
    appId: '1:377354438484:ios:9f17bba97c6171cff12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    iosBundleId: 'com.example.tnpConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInQWxlKfftNsEyo29U91VQqygWgr_uG0',
    appId: '1:377354438484:ios:9f17bba97c6171cff12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    iosBundleId: 'com.example.tnpConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXB0Bgzw5doLRiFkeIHXMS6SctWXR4qfo',
    appId: '1:377354438484:web:f5b1f6863c8046a7f12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    authDomain: 'tpooffice-27b83.firebaseapp.com',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    measurementId: 'G-EV5E836SWE',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXB0Bgzw5doLRiFkeIHXMS6SctWXR4qfo',
    appId: '1:377354438484:web:a793960ec0dffb9cf12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    authDomain: 'tpooffice-27b83.firebaseapp.com',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    measurementId: 'G-BG1HDCYPNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYyfy3DWt2yb3QzQDELyeudKjufr1-aIc',
    appId: '1:377354438484:android:6bba10992680ed79f12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
  );

}