// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInQWxlKfftNsEyo29U91VQqygWgr_uG0',
    appId: '1:377354438484:ios:9f17bba97c6171cff12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    iosBundleId: 'com.example.tnpConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCInQWxlKfftNsEyo29U91VQqygWgr_uG0',
    appId: '1:377354438484:ios:9f17bba97c6171cff12ac1',
    messagingSenderId: '377354438484',
    projectId: 'tpooffice-27b83',
    storageBucket: 'tpooffice-27b83.firebasestorage.app',
    iosBundleId: 'com.example.tnpConnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAYNrGvW35sKdKky7pnp8X7YwhLkRzvOM',
    appId: '1:708673337577:web:bb1c693963501066c19878',
    messagingSenderId: '708673337577',
    projectId: 'placement-app-22030',
    authDomain: 'placement-app-22030.firebaseapp.com',
    storageBucket: 'placement-app-22030.firebasestorage.app',
    measurementId: 'G-P24ZP9W0RW',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYNrGvW35sKdKky7pnp8X7YwhLkRzvOM',
    appId: '1:708673337577:web:826b66689dabc9d6c19878',
    messagingSenderId: '708673337577',
    projectId: 'placement-app-22030',
    authDomain: 'placement-app-22030.firebaseapp.com',
    storageBucket: 'placement-app-22030.firebasestorage.app',
    measurementId: 'G-71L4E53JJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7-YMRR9qtdY3u-M2gomx9MGxR9n3wXtU',
    appId: '1:708673337577:android:6fbf4d070d441683c19878',
    messagingSenderId: '708673337577',
    projectId: 'placement-app-22030',
    storageBucket: 'placement-app-22030.firebasestorage.app',
  );

}